### ISSUE TITLE
Which version torch_geometric you used?

### ISSUE THREAD

**Issue by mw742** [ZimmermanGroup/conformer-rl#66]
Hello 

Thank you for your team's work and it made conformer search quicker and easier.

I was wondering which version  torch_geometric you used in original Torsionnet project and what is your cuda version as well.

So I am trying to run the example.py and it returns this "AttributeError: module 'torch.linalg' has no attribute 'eig'"

I used older version PyTorch 1.8.1 and cuda 10.1. I have installed dependencies for PyTorch 1.8.1 as well. So I guess it is the latest version of torch_geometric is causing the problem because it's expecting a later version of PyTorch. 

I was wondering whether there is older version torch_geometric I can used to run the example.py for a test. As I do not want to upgrade all these packages and reinstall again.....

Hope to hear from you.

**Comment by runxuanjiang** [comment]
Hi,

The library should work with torch 1.8.1 and cuda 10.1. However when you install pytorch geometric you should follow the instructions "installation from wheels" and specify the torch and cuda version when installing:

https://pytorch-geometric.readthedocs.io/en/latest/install/installation.html#installation-from-wheels

Let me know if this helps, thanks

**Comment by runxuanjiang** [comment]
Please see the note at the bottom of step 3 under "installation from wheels" when installing for torch 1.8.1:


> Note: Binaries of older versions are also provided for PyTorch 1.4.0, 1.5.0, 1.6.0, 1.7.0/1.7.1, 1.8.0/1.8.1, 1.9.0, 1.10.0/1.10.1/1.10.2, 1.11.0, 1.12.0/1.12.1 and 1.13.0/1.13.1 (following the same procedure). For older versions, you need to explicitly specify the latest supported version number or install via pip install --no-index in order to prevent a manual installation from source. You can look up the latest supported version number [here](https://data.pyg.org/whl).

**Comment by mw742** [comment]
> Please see the note at the bottom of step 3 under "installation from wheels" when installing for torch 1.8.1:
> 
> > Note: Binaries of older versions are also provided for PyTorch 1.4.0, 1.5.0, 1.6.0, 1.7.0/1.7.1, 1.8.0/1.8.1, 1.9.0, 1.10.0/1.10.1/1.10.2, 1.11.0, 1.12.0/1.12.1 and 1.13.0/1.13.1 (following the same procedure). For older versions, you need to explicitly specify the latest supported version number or install via pip install --no-index in order to prevent a manual installation from source. You can look up the latest supported version number [here](https://data.pyg.org/whl).

Hello

Thank you very much for your reply! 

I did install dependencies following your instructions and this is my final common lines in installing, I found that 1.6.1 is compatible in my environment and it works:
pip install torch-cluster==1.5.9 -f  https://data.pyg.org/whl/torch-1.8.0%2Bcu101/torch_cluster-1.5.9-cp38-cp38-linux_x86_64.whl
pip install torch-scatter==2.0.7 -f  https://data.pyg.org/whl/torch-1.8.0%2Bcu101/torch_scatter-2.0.7-cp38-cp38-linux_x86_64.whl
pip install torch-sparse==0.6.12 -f https://data.pyg.org/whl/torch-1.8.0%2Bcu101/torch_sparse-0.6.12-cp38-cp38-linux_x86_64.whl
pip install torch-spline-conv==1.2.1 -f https://data.pyg.org/whl/torch-1.8.0%2Bcu101/torch_spline_conv-1.2.1-cp38-cp38-linux_x86_64.whl
pip install torch-geometric==1.6.1

In my previous question, I wanted to inquire about the final common line "pip install torch-geometric==?" precise version of torch-geometric. If not specific to its version, the system will install the latest version torch-geometric and it might cause incompatibility later on.

 Thank you very much for you reply!

**Comment by runxuanjiang** [comment]
I believe the version of pytorch_geometric that we used was 2.2.0, as stated in this file: https://github.com/ZimmermanGroup/conformer-rl/blob/master/requirements.txt#L105C23-L105C23

However I think we are using a later version of pytorch than you are (1.13) so not sure if this would be compatible with your setup. It's not clear to me from the pytorch_geometric docs what version of torch-geometric is linked to what specific versions of pytorch, so you may have to ask them directly.

**Comment by mw742** [comment]
> I believe the version of pytorch_geometric that we used was 2.2.0, as stated in this file: https://github.com/ZimmermanGroup/conformer-rl/blob/master/requirements.txt#L105C23-L105C23
> 
> However I think we are using a later version of pytorch than you are (1.13) so not sure if this would be compatible with your setup. It's not clear to me from the pytorch_geometric docs what version of torch-geometric is linked to what specific versions of pytorch, so you may have to ask them directly.

Thank you very much
